language: cpp

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      cache: apt
      before_install:
        - sudo apt-get update -q
        - sudo apt-get install -q cmake libfuse-dev
      script:
        - mkdir build
        - cd build
        - cmake ..
        - make
        - make test
        - modprobe fuse

before_install:
    - eval "${MATRIX_EVAL}"