language: cpp
sudo: required
dist: trusty

os:
- linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - g++-5
      - cmake-data
      - cmake

env:
  - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

compiler:
- gcc

before_install:
  - sudo apt-get update -q
  - sudo apt-get install -q libfuse-dev
  - eval "${MATRIX_EVAL}"

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test
  - modprobe fuse